baseURL = ""
languageCode = "en-us"
theme = "SimpleIntro"
title = "Flunkyball Munich 2022"
publishDir = "public"

[params]
    mainbg = "images/beers.jpg"
    name = "Flipez"
    mainTitle = "English Garden Munich"
    mainText = "18.06.2022 - 12 pm (noon)"

[menus]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "#about"
    [[menu.main]]
        identifier = "rules"
        name = "Rules"
        url = "#rules"
    [[menu.main]]
        identifier = "penalties"
        name = "Penalties"
        url = "#penalties"
